---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-22 - 14:16:07 +0000
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: latest
  name: test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-22 - 14:16:07 +0000
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/version: latest
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
      app.kubernetes.io/version: latest
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-07-22 - 14:16:07 +0000
      labels:
        app.kubernetes.io/name: test
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jorgemclaro/test:latest
          imagePullPolicy: Always
          name: test
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
